# Generated by Django 4.0.6 on 2022-10-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borg', '0003_label_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='compressed_size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='archive',
            name='deduplicated_size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='archive',
            name='file_count',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='archive',
            name='original_size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cache',
            name='total_chunks',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cache',
            name='total_csize',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cache',
            name='total_size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cache',
            name='total_unique_chunks',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cache',
            name='unique_csize',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cache',
            name='unique_size',
            field=models.BigIntegerField(),
        ),
    ]
